name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile_scala:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Compile
      run: sbt backend/compile api/compile webui/compile
  
  compile_js:
    needs: compile_scala
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up npm
      uses: actions/setup-node@v1
    - name: Webpack
      working-directory: ./frontend/webui
      run: npm build
