name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile_scala:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.14
    
    - name: Compile
      run:
        sbt backend/compile api/compile webui/compile
  
  compile_js:
    needs: compile_scala
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup npm
      uses: actions/setup-node@v1
    - name: Install npm
      working-directory: ./frontend/webui
      run:
        npm install
    
    - name: Webpack
      working-directory: ./frontend/webui
      run:
        npm run build
